- name: Install nginx git python3 and pip
  apt: pkg={{ item }} state=present
  with_items:
   - python3
   - python3-pip
   - nginx
   - git

- name: Remove nginx default if exists
  file: path=/etc/nginx/sites-available/default state=absent

- name: Add nginx config to sites-available
  template: src=nginx.conf.j2
            dest=/etc/nginx/sites-available/{{ host }}
  notify:
      - restart nginx

- name: Add symlink in nginx sites-enabled
  file: src=/etc/nginx/sites-available/{{ host }}
        dest=/etc/nginx/sites-enabled/{{ host }} state=link
  notify:
      - restart nginx

- name: Make sure nginx is running
  service: name=nginx state=running